## Naive Baye's Machine Learning Algorithms Implementation

In [117]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [118]:
X,y = load_iris(return_X_y=True)

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [120]:
from sklearn.naive_bayes import GaussianNB

In [121]:
gnb = GaussianNB()

In [122]:
gnb.fit(X_train,y_train)

GaussianNB()

In [123]:
y_pred = gnb.predict(X_test)

In [124]:
from  sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [125]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [126]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

```is pr naive bayes theorm laagni hai caterigical ko nermical data value me convert krna hai ```
```time ko predict krna hai outpout time hoga```

In [127]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [128]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [130]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [131]:
y = df['time']

In [132]:
X = df.drop(columns=['time'])

In [133]:
X.head()

   total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [134]:
## aply onehotEncoding



from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first'), ['sex', 'smoker', 'day'])
    ],
    remainder='passthrough'
)

In [135]:
X = ct.fit_transform(X)

In [136]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

In [137]:

## time to train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,stratify=y
)

In [138]:
X_train.shape

(195, 8)

In [139]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [140]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[32  3]
 [ 0 14]]
0.9387755102040817
              precision    recall  f1-score   support

           0       1.00      0.91      0.96        35
           1       0.82      1.00      0.90        14

    accuracy                           0.94        49
   macro avg       0.91      0.96      0.93        49
weighted avg       0.95      0.94      0.94        49

### ```Try other models on same data ```

In [141]:

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [142]:
models = {
    "Logistic Regression": LogisticRegression(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "GaussianNB": GaussianNB()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{name} : {accuracy_score(y_test, y_pred):.4f}")

Logistic Regression : 0.9388
KNN : 0.8776
SVM : 0.7143
Decision Tree : 0.9184
GaussianNB : 0.9388