In [9]:
import pandas as pd

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
## Create a simple dataframe 
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [12]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [13]:
encoder = OneHotEncoder()

In [18]:
encoded = encoder.fit_transform(df[['color']]).toarray()

In [19]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [16]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [17]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0