## Part I-Text Classification With Word2vec And AvgWord2vec

In [2]:
! pip install gensim

Requirement already satisfied: gensim in c:\users\dev_manish\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\dev_manish\anaconda3\lib\site-packages (from gensim) (2.3.5)
Requirement already satisfied: scipy>=1.7.0 in c:\users\dev_manish\anaconda3\lib\site-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\dev_manish\anaconda3\lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in c:\users\dev_manish\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [3]:
from gensim.models import word2vec,keyedvectors

In [4]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

vec_king = wv['king']

In [5]:
import pandas as pd

messages = pd.read_csv('SMSSpamCollection.csv',sep='\t',names=['label','message'])
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
import re
import nltk
nltk.download("stopwords")
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DEV_MANISH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [7]:
corpus = []

for i in range(0,len(messages)):
    review= re.sub('^[Aa-zA-z]',' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word)for word  in review]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[]

In [9]:
corpus

['o until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...',
 'k lar... joking wif u oni...',
 "ree entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'dun say so early hor... u c already then say...',
 "ah i don't think he go to usf, he life around here though",
 "reemsg hey there darling it's been 3 week's now and no word back! i'd like some fun you up for it still? tb ok! xxx std chgs to send, £1.50 to rcv",
 'ven my brother is not like to speak with me. they treat me like aid patent.',
 "s per your request 'melle melle (oru minnaminunginte nurungu vettam)' ha been set a your callertune for all callers. press *9 to copy your friend callertune",
 'inner!! a a valued network customer you have been selected to receivea £900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hour only.',
 'ad your mobile 11 month or more? u r entitled to update to the latest colour mobile with camera for free! call the mobile update co free on 08002986030',
 "'m gonna be home soon and i don't want to talk about this stuff anymore tonight, k? i've cried enough today.",
 'ix chance to win cash! from 100 to 20,000 pound txt> csh11 and send to 87575. cost 150p/day, 6days, 16+ tsandcs apply reply hl 4 info',
 'rgent! you have won a 1 week free membership in our £100,000 prize jackpot! txt the word: claim to no: 81010 t&c www.dbuk.net lccltd pobox 4403ldnw1a7rw18',
 "'ve been searching for the right word to thank you for this breather. i promise i wont take your help for granted and will fulfil my promise. you have been wonderful and a blessing at all times.",
 'have a date on sunday with will!!',
 'xxmobilemovieclub: to use your credit, click the wap link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=qjkgighjjgcbl',
 "h k...i'm watching here:)",
 'h u remember how 2 spell his name... yes i did. he v naughty make until i v wet.',
 'ine if that\x92s the way u feel. that\x92s the way it gota b',
 'ngland v macedonia - dont miss the goals/team news. txt ur national team to 87077 eg england to 87077 try:wales, scotland 4txt/ú1.20 poboxox36504w45wq 16+',
 's that seriously how you spell his name?',
 '‘m going to try for 2 month ha ha only joking',
 'o ü pay first lar... then when is da stock comin...',
 'ft i finish my lunch then i go str down lor. ard 3 smth lor. u finish ur lunch already?',
 'fffffffff. alright no way i can meet up with you sooner?',
 "ust forced myself to eat a slice. i'm really not hungry tho. this sucks. mark is getting worried. he know i'm sick when i turn down pizza. lol",
 'ol your always so convincing.',
 "id you catch the bus ? are you frying an egg ? did you make a tea? are you eating your mom's left over dinner ? do you feel my love ?",
 "'m back &amp; we're packing the car now, i'll let you know if there's room",
 'hhh. work. i vaguely remember that! what doe it feel like? lol',
 "ait that's still not all that clear, were you not sure about me being sarcastic or that that's why x doesn't want to live with u",
 "eah he got in at 2 and wa v apologetic. n had fallen out and she wa actin like spoilt child and he got caught up in that. till 2! but we won't go there! not doing too badly cheers. you?",
 'tell me anything about you.',
 'or fear of fainting with the of all that housework you just did? quick have a cuppa',
 'hank for your subscription to ringtone uk your mobile will be charged £5/month please confirm by replying yes or no. if you reply no you will not be charged',
 'up... ok i go home look at the timing then i msg ü again... xuhui going to learn on 2nd may too but her lesson is at 8am',
 "ops, i'll let you know when my roommate's done",
 'see the letter b on my car',
 'nything lor... u decide...',
 "ello! how's you and how did saturday go? i wa just texting to see if you'd decided to do anything tomo. not that i'm trying to invite myself or anything!",
 'l go ahead with watts. i just wanted to be sure. do have a great weekend. abiola',
 'id i forget to tell you ? i want you , i need you, i crave you ... but most of all ... i love you my sweet arabian steed ... mmmmmm ... yummy',
 '07732584351 - rodger burn - msg = we tried to call you re your reply to our sm for a free nokia mobile + free camcorder. please call now 08000930705 for delivery tomorrow',
 'ho are you seeing?',
 'reat! i hope you like your man well endowed. i am &lt;#&gt; inches...',
 'o calls..messages..missed call',
 "idn't you get hep b immunisation in nigeria.",
 'air enough, anything going on?',
 "eah hopefully, if tyler can't do it i could maybe ask around a bit",
 "don't know how stubborn i am. i didn't even want to go to the hospital. i kept telling mark i'm not a weak sucker. hospital are for weak suckers.",
 'hat you thinked about me. first time you saw me in class.',
 'gram usually run like &lt;#&gt; , a half eighth is smarter though and get you almost a whole second gram for &lt;#&gt;',
 "fyi x ha a ride early tomorrow morning but he's crashing at our place tonight",
 'ow. i never realized that you were so embarassed by your accomodations. i thought you liked it, since i wa doing the best i could and you always seemed so happy about "the cave". i\'m sorry i didn\'t and don\'t have more to give. i\'m sorry i offered. i\'m sorry your room wa so embarassing.',
 'ms. ac sptv: the new jersey devil and the detroit red wing play ice hockey. correct or incorrect? end? reply end sptv',
 'o you know what mallika sherawat did yesterday? find out now @ &lt;url&gt;',
 'ongrats! 1 year special cinema pas for 2 is yours. call 09061209465 now! c suprman v, matrix3, starwars3, etc all 4 free! bx420-ip4-5we. 150pm. dont miss out!',
 "orry, i'll call later in meeting.",
 'ell where you reached',
 'es..gauti and sehwag out of odi series.',
 "our gonna have to pick up a $1 burger for yourself on your way home. i can't even move. pain is killing me.",
 'a ha ha good joke. girl are situation seekers.',
 't a part of checking iq',
 'orry my roommate took forever, it ok if i come by now?',
 'k lar i double check wif da hair dresser already he said wun cut v short. he said will cut until i look nice.',
 's a valued customer, i am pleased to advise you that following recent review of your mob no. you are awarded with a £1500 bonus prize, call 09066364589',
 'oday is "song dedicated day.." which song will u dedicate for me? send this to all ur valuable frnds but first rply me...',
 'rgent ur awarded a complimentary trip to eurodisinc trav, aco&entry41 or £1000. to claim txt dis to 87121 18+6*£1.50(morefrmmob. shracomorsglsuplt)10, ls1 3aj',
 'id you hear about the new "divorce barbie"? it come with all of ken\'s stuff!',
 'plane to give on this month end.',
 'ah lucky man... then can save money... hee...',
 'inished class where are you.',
 'i babe im at home now wanna do something? xx',
 '..k:)where are you?how did you performed?',
 'can call me now...',
 'am waiting machan. call me once you free.',
 'hat cool. i am a gentleman and will treat you with dignity and respect.',
 'like you people very much:) but am very shy pa.',
 'oes not operate after &lt;#&gt; or what',
 "t not the same here. still looking for a job. how much do ta's earn there.",
 "orry, i'll call later",
 '. did you call me just now ah?',
 'k i am on the way to home hi hi',
 'ou will be in the place of that man',
 'up next stop.',
 "call you later, don't have network. if urgnt, sm me.",
 "or real when u getting on yo? i only need 2 more ticket and one more jacket and i'm done. i already used all my multis.",
 "e i started to send request to make it but pain came back so i'm back in bed. double coin at the factory too. i gotta cash in all my nitros.",
 "'m really not up to it still tonight babe",
 'la kano.,il download, come wen ur free..',
 'eah do! don‘t stand to close tho- you‘ll catch something!',
 "orry to be a pain. is it ok if we meet another night? i spent late afternoon in casualty and that mean i haven't done any of y stuff42moro and that includes all my time sheet and that. sorry.",
 'mile in pleasure smile in pain smile when trouble pours like rain smile when sum1 hurt u smile becoz someone still love to see u smiling!!',
 'lease call our customer service representative on 0800 169 6031 between 10am-9pm a you have won a guaranteed £1000 cash or £5000 prize!',
 'avent planning to buy later. i check already lido only got 530 show in e afternoon. u finish work already?',
 'our free ringtone is waiting to be collected. simply text the password "mix" to 85069 to verify. get usher and britney. fml, po box 5249, mk17 92h. 450ppw 16',
 'atching telugu movie..wat abt u?',
 'see. when we finish we have load of loan to pay',
 'i. wk been ok - on hols now! yes on for a bit of a run. forgot that i have hairdresser appointment at four so need to get home n shower beforehand. doe that cause prob for u?"',
 'see a cup of coffee animation',
 "lease don't text me anymore. i have nothing else to say.",
 'kay name ur price a long a it legal! wen can i pick them up? y u ave x am xx',
 "'m still looking for a car to buy. and have not gone 4the driving test yet.",
 "s per your request 'melle melle (oru minnaminunginte nurungu vettam)' ha been set a your callertune for all callers. press *9 to copy your friend callertune",
 "ow. you're right! i didn't mean to do that. i guess once i gave up on boston men and changed my search location to nyc, something changed. cuz on my signin page it still say boston.",
 'mma my life and vava umma love you lot dear',
 'hank a lot for your wish on my birthday. thanks you for making my birthday truly memorable.',
 "ight, i'll hit you up when i get some cash",
 "ow would my ip address test that considering my computer isn't a minecraft server",
 'know! grumpy old people. my mom wa like you better not be lying. then again i am always the one to play jokes...',
 "ont worry. i guess he's busy.",
 'hat is the plural of the noun research?',
 'oing for dinner.msg you after.',
 "'m ok wif it co i like 2 try new things. but i scared u dun like mah. co u said not too loud.",
 'ent! we are trying to contact you. last weekend draw show that you won a £1000 prize guaranteed. call 09064012160. claim code k52. valid 12hrs only. 150ppm',
 "a, ur openin sentence very formal... anyway, i'm fine too, juz tt i'm eatin too much n puttin on weight...haha... so anythin special happened?",
 "s i entered my cabin my pa said, '' happy b'day bos !!''. i felt special. she askd me 4 lunch. after lunch she invited me to her apartment. we went there.",
 'ou are a winner u have been specially selected 2 receive £1000 or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810910p/min (18+)',
 'oodo! yes we must speak friday - egg-potato ratio for tortilla needed!',
 "mm...my uncle just informed me that he's paying the school directly. so pls buy food.",
 'rivate! your 2004 account statement for 07742676969 show 786 unredeemed bonus points. to claim call 08719180248 identifier code: 45239 expires',
 'rgent! your mobile no. wa awarded £2000 bonus caller prize on 5/9/03 this is our final try to contact u! call from landline 09064019788 box42wr29c, 150ppm',
 'ere is my new address -apples&pairs&all that malarky',
 'odays voda number ending 7548 are selected to receive a $350 award. if you have a match please call 08712300220 quoting claim code 4041 standard rate app',
 'am going to sao mu today. will be done only at 12',
 "ü predict wat time ü'll finish buying?",
 'ood stuff, will do.',
 "ust so that you know,yetunde hasn't sent money yet. i just sent her a text not to bother sending. so it over, you dont have to involve yourself in anything. i shouldn't have imposed anything on you in the first place so for that, i apologise.",
 're you there in room.',
 'ey girl. how r u? hope u r well me an del r bak! again long time no c! give me a call sum time from lucyxx',
 '..k:)how much doe it cost?',
 "'m home.",
 'ear, will call tmorrow.pls accomodate.',
 'irst answer my question.',
 'unshine quiz wkly q! win a top sony dvd player if u know which country the algarve is in? txt ansr to 82277. £1.50 sp:tyrone',
 "ant 2 get laid tonight? want real dogging location sent direct 2 ur mob? join the uk's largest dogging network bt txting gravel to 69888! nt. ec2a. 31p.msg@150p",
 "only haf msn. it's yijue@hotmail.com",
 'e is there. you call and meet him',
 'o no. i will check all room befor activity',
 "ou'll not rcv any more msg from the chat svc. for free hardcore service text go to: 69988 if u get nothing u must age verify with yr network & try again",
 'ot c... i lazy to type... i forgot ü in lect... i saw a pouch but like not v nice...',
 ", text me when you're on the way",
 'ir, waiting for your mail.',
 'swt thought: "nver get tired of doing little thing 4 lovable persons.." coz..somtimes those little thing occupy d biggest part in their hearts.. gud ni8',
 'know you are. can you pls open the back?',
 'e see ya not on the dot',
 'hat the staff name who is taking class for us?',
 "reemsg why haven't you replied to my text? i'm randy, sexy, female and live local. luv to hear from u. netcollex ltd 08700621170150p per msg reply stop to end",
 'mmma.will call after check in.our life will begin from qatar so pls pray very hard.',
 '..i deleted my contact that why?',
 'indu got job in birla soft ..',
 "he wine is flowing and i'm i have nevering..",
 'up i thk cine is better co no need 2 go down 2 plaza mah.',
 'k... ur typical reply...',
 "s per your request 'melle melle (oru minnaminunginte nurungu vettam)' ha been set a your callertune for all callers. press *9 to copy your friend callertune",
 'ou are everywhere dirt, on the floor, the windows, even on my shirt. and sometimes when i open my mouth, you are all that come flowing out. i dream of my world without you, then half my chore are out too. a time of joy for me, lot of tv show i.ll see. but i guess like all thing you just must exist, like rain, hail and mist, and when my time here is done, you and i become one.',
 'aooooright are you at work?',
 "'m leaving my house now...",
 'ello, my love. what are you doing? did you get to that interview today? are you you happy? are you being a good boy? do you think of me?are you missing me ?',
 'ustomer service annoncement. you have a new year delivery waiting for you. please call 07046744435 now to arrange delivery',
 'ou are a winner u have been specially selected 2 receive £1000 cash or a 4* holiday (flights inc) speak to a live operator 2 claim 0871277810810',
 "eep yourself safe for me because i need you and i miss you already and i envy everyone that see's you in real life",
 'ew car and house for my parents.:)i have only new job in hand:)',
 "'m so in love with you. i'm excited each day i spend with you. you make me so happy.",
 '-pls stop bootydelious (32/f) is inviting you to be her friend. reply yes-434 or no-434 see her: www.sms.ac/u/bootydelious stop? send stop frnd to 62468',
 'angbabes ur order is on the way. u should receive a service msg 2 download ur content. if u do not, goto wap. bangb. tv on ur mobile internet/service menu',
 'place all ur point on e culture module already.',
 'rgent! we are trying to contact you. last weekend draw show that you have won a £900 prize guaranteed. call 09061701939. claim code s89. valid 12hrs only',
 "i frnd, which is best way to avoid missunderstding wit our beloved one's?",
 'reat escape. i fancy the bridge but need her lager. see you tomo',
 'e :)it completely in out of form:)clark also utter waste.',
 'ir, i need axis bank account no and bank address.',
 'mmm.. thk sure got time to hop ard... ya, can go 4 free abt... muz call u to discus liao...',
 'hat time you coming down later?',
 'loody hell, cant believe you forgot my surname mr . ill give u a clue, it spanish and begin with m...',
 "ell, i'm gonna finish my bath now. have a good...fine night.",
 "et me know when you've got the money so carlos can make the call",
 'still going to the mall?',
 "urn out my friend are staying for the whole show and won't be back til ~ &lt;#&gt; , so feel free to go ahead and smoke that $ &lt;#&gt; worth",
 'ext her. if she doesnt reply let me know so i can have her log in',
 "i! you just spoke to maneesha v. we'd like to know if you were satisfied with the experience. reply toll free with yes or no.",
 'ou lifted my hope with the offer of money. i am in need. especially when the end of the month approach and it hurt my studying. anyways have a gr8 weekend',
 'ol no. u can trust me.',
 'k. i am a gentleman and will treat you with dignity and respect.',
 'e will, you guy close?',
 'oing on nothing great.bye',
 "ello handsome ! are you finding that job ? not being lazy ? working towards getting back that net for mummy ? where's my boytoy now ? doe he miss me ?",
 'aha awesome, be there in a minute',
 'lease call our customer service representative on freephone 0808 145 4742 between 9am-11pm a you have won a guaranteed £1000 cash or £5000 prize!',
 'ave you got xmas radio times. if not i will get it now',
 'jus reached home. i go bathe first. but my si using net tell u when she finish k...',
 're you unique enough? find out from 30th august. www.areyouunique.co.uk',
 "'m sorry. i've joined the league of people that dont keep in touch. you mean a great deal to me. you have been a friend at all time even at great personal cost. do have a great week.|",
 'i :)finally i completed the course:)',
 't will stop on itself. i however suggest she stay with someone that will be able to give or for every stool.',
 "ow are you doing? hope you've settled in for the new school year. just wishin you a gr8 day",
 'ud mrng dear hav a nice day',
 'id u got that person story',
 's your hamster dead? hey so tmr i meet you at 1pm orchard mrt?',
 'i it kate how is your evening? i hope i can see you tomorrow for a bit but i have to bloody babyjontet! txt back if u can. :) xxx',
 'ound it, enc &lt;#&gt; , where you at?',
 'sent you &lt;#&gt; buck',
 'ello darlin ive finished college now so txt me when u finish if u can love kate xxx',
 'our account ha been refilled successfully by inr &lt;decimal&gt; . your keralacircle prepaid account balance is r &lt;decimal&gt; . your transaction id is kr &lt;#&gt; .',
 'oodmorning sleeping ga.',
 'call me alter at 11 ok.',
 'ü say until like dat i dun buy ericsson oso cannot oredi lar...',
 "s i entered my cabin my pa said, '' happy b'day bos !!''. i felt special. she askd me 4 lunch. after lunch she invited me to her apartment. we went there.",
 'ight yo, dat straight dogg',
 'ou please give u connection today itself before &lt;decimal&gt; or refund the bill',
 'oth :) i shoot big load so get ready!',
 "hat's up bruv, hope you had a great break. do have a rewarding semester.",
 'ome so we can always chat',
 ':)k:)good:)study well.',
 'up... how ü noe leh...',
 'ounds great! are you home now?',
 'inally the match heading towards draw a your prediction.',
 "ired. i haven't slept well the past few nights.",
 'asy ah?sen got selected mean it good..',
 'have to take exam with march 3',
 "eah you should. i think you can use your gt atm now to register. not sure but if there's anyway i can help let me know. but when you do be sure you are ready.",
 'k no prob. take ur time.',
 'here is o called ubandu which will run without installing in hard disk...you can use that o to copy the important file in system and give it to repair shop..',
 "orry, i'll call later",
 'say leh... of course nothing happen lar. not say v romantic jus a bit only lor. i thk e nite scenery not so nice leh.',
 '500 new mobile from 2004, must go! txt: nokia to no: 89545 & collect yours today!from only £1 www.4-tc.biz 2optout 087187262701.50gbp/mtmsg18',
 'ould really appreciate if you call me. just need someone to talk to.',

In [10]:
# shortcut for the upper code
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [11]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    words.append(simple_preprocess(sent))

In [12]:
words

[['until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['lar', 'joking', 'wif', 'oni'],
 ['ree',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['ah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['reemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['ven',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['inner',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['ad',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cried',
  'enough',
  'today'],
 ['ix',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'days',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['rgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'blessing',
  'at',
  'all',
  'times'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['watching', 'here'],
 ['remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'did',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['ine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['ngland',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goals',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wales',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'],
 ['pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['ft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['fffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['ust',
  'forced',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'sucks',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['ol', 'your', 'always', 'so', 'convincing'],
 ['id',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['hhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['ait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with'],
 ['eah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologetic',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheers',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['or',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['hank',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['up',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['ops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['nything', 'lor', 'decide'],
 ['ello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['go',
  'ahead',
  'with',
  'watts',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['id',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['ho', 'are', 'you', 'seeing'],
 ['reat',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'am',
  'lt',
  'gt',
  'inches'],
 ['calls', 'messages', 'missed', 'call'],
 ['idn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['air', 'enough', 'anything', 'going', 'on'],
 ['eah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'kept',
  'telling',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'suckers'],
 ['hat',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['ow',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'wa',
  'doing',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offered',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['ms',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['ongrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['orry', 'll', 'call', 'later', 'in', 'meeting'],
 ['ell', 'where', 'you', 'reached'],
 ['es', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['our',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seekers'],
 ['part', 'of', 'checking', 'iq'],
 ['orry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['valued',
  'customer',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'bonus',
  'prize',
  'call'],
 ['oday',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['rgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'ls',
  'aj'],
 ['id',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['ah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['inished', 'class', 'where', 'are', 'you'],
 ['babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['can', 'call', 'me', 'now'],
 ['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['hat',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'],
 ['oes', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['orry', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['ou', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['up', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['or',
  'real',
  'when',
  'getting',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['la', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['eah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['orry',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['mile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smiling'],
 ['lease',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'you',
  'have',
  'won',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['avent',
  'planning',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['our',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['atching', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['lease',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['kay',
  'name',
  'ur',
  'price',
  'long',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'looking',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['ow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['mma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['hank',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['ight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['ow',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'jokes'],
 ['ont', 'worry', 'guess', 'he', 'busy'],
 ['hat', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['oing', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'try',
  'new',
  'things',
  'but',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['ent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hrs',
  'only',
  'ppm'],
 ['ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['ou',
  'are',
  'winner',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'holiday',
  'flights',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['oodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['mm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['rivate',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'points',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['rgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['ere',
  'is',
  'my',
  'new',
  'address',
  'apples',
  'pairs',
  'all',
  'that',
  'malarky'],
 ['odays',
  'voda',
  'number',
  'ending',
  'are',
  'selected',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am',
  'going',
  'to',
  'sao',
  'mu',
  'today',
  'will',
  'be',
  'done',
  'only',
  'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buying'],
 ['ood', 'stuff', 'will', 'do'],
 ['ust',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'sending',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'imposed',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['re', 'you', 'there', 'in', 'room'],
 ['ey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['ear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['irst', 'answer', 'my', 'question'],
 ['unshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['ant',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'the',
  'uk',
  'largest',
  'dogging',
  'network',
  'bt',
  'txting',
  'gravel',
  'to',
  'nt',
  'ec',
  'msg'],

In [13]:
import gensim

In [14]:
## lets train word2ec from scratch
model = gensim.models.Word2Vec(words)

In [15]:
## get all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'in',
 'it',
 'is',
 'me',
 'my',
 'for',
 'your',
 'of',
 'call',
 'have',
 'on',
 'that',
 'now',
 'are',
 'or',
 'can',
 'but',
 'at',
 'not',
 'so',
 'get',
 'be',
 'ur',
 'with',
 'will',
 'we',
 'do',
 'if',
 'up',
 'just',
 'gt',
 'lt',
 'this',
 'go',
 'll',
 'all',
 'from',
 'when',
 'out',
 'day',
 'know',
 'no',
 'he',
 'free',
 'how',
 'like',
 'time',
 'come',
 'got',
 'am',
 'wa',
 'what',
 'there',
 'then',
 'only',
 'love',
 'text',
 'want',
 'good',
 'send',
 'need',
 'one',
 'txt',
 'by',
 'going',
 'our',
 'home',
 'about',
 'stop',
 'an',
 'lor',
 'today',
 'here',
 'see',
 'ok',
 're',
 'mobile',
 'don',
 'take',
 'back',
 'da',
 'she',
 'still',
 'reply',
 'think',
 'phone',
 'ou',
 'week',
 'later',
 'her',
 'any',
 'been',
 'new',
 'tell',
 'dont',
 'co',
 'ha',
 'some',
 'make',
 'they',
 'msg',
 'who',
 'hat',
 'much',
 'claim',
 'say',
 'night',
 'him',
 'please',
 'pls',
 'did',
 'more',
 'number',
 'too',
 'give',
 'work',
 'message',
 'thing',
 'min',
 'hope',
 'way',
 'www',
 've',
 'orry',
 'where',
 'happy',
 'had',
 'ey',
 'won',
 'prize',
 'great',
 'right',
 'should',
 'tomorrow',
 'said',
 'his',
 'friend',
 'already',
 'ow',
 'ask',
 'amp',
 'cash',
 'after',
 'let',
 'dear',
 'wat',
 'doing',
 'find',
 'tone',
 'them',
 'meet',
 'very',
 'well',
 'really',
 'life',
 'morning',
 'miss',
 'win',
 'uk',
 'care',
 'com',
 'last',
 'im',
 'service',
 'nokia',
 'would',
 'feel',
 'every',
 'contact',
 'year',
 'why',
 'over',
 'keep',
 'something',
 'babe',
 'pick',
 'sent',
 'again',
 'anything',
 'before',
 'box',
 'cant',
 'buy',
 'place',
 'sure',
 'sorry',
 'first',
 'help',
 'next',
 'off',
 'also',
 'end',
 'tonight',
 'around',
 'wait',
 'wish',
 'even',
 'soon',
 'sleep',
 'gud',
 'chat',
 'went',
 'show',
 'late',
 'could',
 'were',
 'per',
 'guy',
 'money',
 'which',
 'always',
 'gonna',
 'many',
 'nice',
 'down',
 'name',
 'someone',
 'ell',
 'nd',
 'wan',
 'hen',
 'other',
 'lot',
 'pm',
 'leave',
 'told',
 'special',
 'rgent',
 'customer',
 'word',
 'dun',
 'st',
 'person',
 'ot',
 'ill',
 'coming',
 'people',
 'eah',
 'ol',
 'th',
 'yet',
 'guaranteed',
 'waiting',
 'girl',
 'try',
 'ppm',
 'best',
 'done',
 'getting',
 'use',
 'may',
 'thk',
 'fine',
 'heart',
 'start',
 'minute',
 'ood',
 'holiday',
 'thanks',
 'hour',
 'line',
 'offer',
 'thought',
 'class',
 'didn',
 'bit',
 'live',
 'lunch',
 'stuff',
 'month',
 'few',
 'mean',
 'job',
 'man',
 'ust',
 'yes',
 'cost',
 'ear',
 'smile',
 'same',
 'being',
 'car',
 'id',
 'ah',
 'god',
 'draw',
 'trying',
 'finish',
 'talk',
 'problem',
 'ready',
 'dat',
 'account',
 'hank',
 'pobox',
 'rate',
 'mind',
 'having',
 'better',
 'hi',
 'meeting',
 'chance',
 'plan',
 'ya',
 'wk',
 'real',
 'never',
 'half',
 'weekend',
 'world',
 'oh',
 'than',
 'because',
 'house',
 'bt',
 'ight',
 'long',
 'room',
 'ree',
 'luv',
 'po',
 'awarded',
 'play',
 'latest',
 'receive',
 'lar',
 'liao',
 'enjoy',
 'ever',
 'into',
 'yeah',
 'aha',
 'birthday',
 'another',
 'sweet',
 'dinner',
 'eat',
 'xxx',
 'shit',
 'cs',
 'video',
 'voucher',
 'big',
 'wanna',
 'pic',
 'thats',
 'might',
 'landline',
 'ave',
 'check',
 'ello',
 'look',
 'wont',
 'watch',
 'called',
 'boy',
 'tv',
 'guess',
 'bed',
 'pa',
 'hear',
 'till',
 'camera',
 'kiss',
 'bad',
 'quite',
 'baby',
 'age',
 'part',
 'bus',
 'pay',
 'speak',
 'fun',
 'early',
 'apply',
 'office',
 'sat',
 'orange',
 'two',
 'made',
 'reach',
 'between',
 'left',
 'code',
 'hey',
 'princess',
 'den',
 'put',
 'didnt',
 'everything',
 'face',
 'nite',
 'leh',
 'little',
 'award',
 'hrs',
 'worry',
 'cool',
 'once',
 'xx',
 'ringtone',
 'network',
 'town',
 'game',
 'shopping',
 'evening',
 'working',
 'mail',
 'forgot',
 'looking',
 'dis',
 'es',
 'remember',
 'enough',
 'selected',
 'question',
 'while',
 'easy',
 'gift',
 'without',
 'school',
 'hurt',
 'afternoon',
 'run',
 'pound',
 'entry',
 'dad',
 'ope',
 'asked',
 'collect',
 'hav',
 'missing',
 'price',
 'nothing',
 'movie',
 'came',
 'pain',
 'maybe',
 'most',
 'wanted',
 'valid',
 'though',
 'collection',
 'fuck',
 'wife',
 'sir',
 'true',
 'tmr',
 'able',
 'jus',
 'til',
 'those',
 'join',
 'top',
 'must',
 'anyway',
 'abt',
 'mob',
 'since',
 'sm',
 'wif',
 'until',
 'probably',
 'plus',
 'away',
 'de',
 'actually',
 'charge',
 'wake',
 'decimal',
 'stay',
 'sexy',
 'answer',
 'doe',
 'date',
 'ad',
 'attempt',
 'weekly',
 'shall',
 'mins',
 'music',
 'else',
 'lease',
 'hair',
 'missed',
 'lol',
 'watching',
 'colour',
 'lei',
 'bring',
 'online',
 'drink',
 'change',
 'book',
 'plz',
 'ring',
 'optout',
 'important',
 'oso',
 'xmas',
 'et',
 'coz',
 'food',
 'haha',
 'juz',
 'making',
 'yours',
 'yesterday',
 'saw',
 'net',
 'update',
 'goin',
 'family',
 'sch',
 'these',
 'either',
 'feeling',
 'detail',
 'club',
 'shop',
 'yr',
 'player',
 'ont',
 'address',
 'test',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'national',
 'mate',
 'together',
 'un',
 'bored',
 'lose',
 'sae',
 'tot',
 'head',
 'calling',
 'wid',
 'thanx',
 'walk',
 'story',
 'believe',
 'order',
 'sms',
 'dream',
 'haf',
 'trip',
 'bonus',
 'lesson',
 'days',
 'brother',
 'await',
 'drive',
 'both',
 'saying',
 'eve',
 'poly',
 'chikku',
 'row',
 'post',
 'full',
 'happen',
 'noe',
 'smoke',
 'busy',
 'old',
 'smiling',
 'haven',
 'second',
 'reat',
 'ard',
 'http',
 'info',
 'drop',
 'rite',
 'pub',
 'simple',
 'its',
 'land',
 'suite',
 'hello',
 'mths',
 'wot',
 'friendship',
 'sound',
 'wil',
 'sleeping',
 'gr',
 'leaving',
 'nt',
 'close',
 'wen',
 'started',
 'took',
 'tomo',
 'news',
 'hl',
 'set',
 'anyone',
 'email',
 'aft',
 'ar',
 'ay',
 'thinking',
 'ut',
 'havent',
 'dunno',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'break',
 'finished',
 'touch',
 'si',
 'content',
 'everyone',
 'taking',
 'statement',
 'hit',
 'cause',
 'forget',
 'doesn',
 'tho',
 'credit',
 'available',
 'neva',
 'auction',
 'alone',
 'loving',
 'okay',
 'knw',
 'mine',
 'opt',
 'gd',
 'urgent',
 'bout',
 'reason',
 'friends',
 'choose',
 'hot',
 'worth',
 'bank',
 'each',
 'hand',
 'type',
 'expires',
 'search',
 'yo',
 'lucky',
 'double',
 'mom',
 'treat',
 'point',
 'sad',
 'fast',
 'visit',
 'nyt',
 'dating',
 'mobileupd',
 'found',
 'far',
 'company',
 'gbp',
 'tc',
 'college',
 'boytoy',
 'fancy',
 'ltd',
 'open',
 'ni',
 'quiz',
 'match',
 'identifier',
 'points',
 'rivate',
 'friday',
 'gone',
 'prob',
 'ticket',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'final',
 'chennai',
 'rd',
 'least',
 'whats',
 'wonder',
 'sun',
 'valentine',
 'mum',
 'whatever',
 'sea',
 'pretty',
 'fri',
 'outside',
 'beautiful',
 'fucking',
 'lands',
 'light',
 'read',
 'as',
 'hy',
 'hold',
 'tel',
 'secret',
 'exam',
 'ome',
 'oredi',
 'darlin',
 'mrng',
 'mr',
 'wit',
 'frnd',
 'mu',
 'operator',
 'happened',
 'used',
 'camcorder',
 'thank',
 'wasn',
 'abe',
 'support',
 'party',
 'earlier',
 'wrong',
 'lovely',
 'gal',
 'drug',
 'snow',
 'listen',
 'sub',
 'savamob',
 'frm',
 'cum',
 'kind',
 'ten',
 'lright',
 'sk',
 'project',
 'ish',
 'fone',
 'blue',
 'anytime',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'mm',
 'frnds',
 'ice',
 'ac',
 'whole',
 'telling',
 'calls',
 'seeing',
 'ho',
 'wq',
 'sunday',
 'reemsg',
 'wkly',
 'crazy',
 'father',
 'gas',
 'john',
 'hr',
 'enter',
 'luck',
 'na',
 'gn',
 'knew',
 'lso',
 'store',
 'mayb',
 'unno',
 'sell',
 'paper',
 'area',
 'happiness',
 'appy',
 'within',
 'park',
 'term',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'ool',
 'dude',
 'lost',
 'bslvyl',
 'unlimited',
 'cd',
 'fr',
 'side',
 'march',
 'balance',
 'finally',
 'hard',
 'us',
 'ir',
 'caller',
 'uncle',
 'winner',
 'invited',
 'felt',
 'isn',
 'hee',
 'oday',
 'cut',
 'move',
 'etc',
 'ongrats',
 'hungry',
 'valued',
 'press',
 'parent',
 'dreams',
 'difficult',
 'film',
 'grins',
 'surprise',
 'information',
 'heard',
 'sort',
 'understand',
 'extra',
 'picking',
 'sex',
 'gym',
 'through',
 'max',
 'redeemed',
 'ipod',
 'doin',
 'supposed',
 'india',
 'uh',
 'rental',
 'seen',
 'ex',
 'met',
 'via',
 'return',
 'reading',
 'christmas',
 'games',
 'ge',
 'swing',
 'hanx',
 'dnt',
 'en',
 'ongratulations',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'ive',
 'mmm',
 'tired',
 'direct',
 'ant',
 'askd',
 'mah',
 'computer',
 'shower',
 'load',
 'download',
 'gotta',
 'red',
 'almost',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'la',
 'police',
 'hows',
 'slowly',
 'loved',
 'fact',
 'truth',
 'photo',
 'asap',
 'ude',
 'whenever',
 'ma',
 'xy',
 'ts',
 'darren',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'monday',
 'remove',
 'othing',
 'ure',
 'welcome',
 'rock',
 'slow',
 'discount',
 'hg',
 'weed',
 'rest',
 'die',
 'kie',
 'leaf',
 'single',
 'wana',
 'own',
 'study',
 'bill',
 'orchard',
 'carlos',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'sending',
 'entered',
 'things',
 'kay',
 'il',
 'complimentary',
 'rply',
 'checking',
 'pas',
 'correct',
 'messages',
 'crave',
 'abiola',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'std',
 'empty',
 'med',
 'eye',
 'hw',
 'write',
 'bb',
 'ringtones',
 'rs',
 'energy',
 'iya',
 'cr',
 'ntt',
 'getzed',
 'fantastic',
 'gap',
 'king',
 'laugh',
 'kid',
 'eh',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'ove',
 'different',
 'asking',
 'wc',
 'ldn',
 'voice',
 'woke',
 'rakhesh',
 'figure',
 'small',
 'custcare',
 'immediately',
 'normal',
 'uz',
 'tonite',
 'usual',
 'wesome',
 'lover',
 'deep',
 ...]

In [16]:
model.corpus_count

5572

In [17]:
model.epochs

5

In [18]:
model.wv.similar_by_word("good")

[('here', 0.9993079900741577),
 ('happy', 0.9992314577102661),
 ('wa', 0.9992002844810486),
 ('amp', 0.9991706013679504),
 ('where', 0.9991387128829956),
 ('should', 0.9991369247436523),
 ('morning', 0.9991368055343628),
 ('that', 0.9991355538368225),
 ('about', 0.9991271495819092),
 ('very', 0.9990603923797607)]

In [19]:
model.wv['good'].shape

(100,)

In [20]:
words[0]

['until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

## average Word2Vec

In [21]:
import numpy as np

def avg_word2vec(doc):

    # Remove out-of-vocabulary words
    sent = [word for word in doc if word in model.wv.index_to_key]

    # Agar koi valid word nahi mila
    if len(sent) == 0:
        return np.zeros(model.vector_size)

    return np.mean([model.wv[word] for word in sent], axis=0)

In [22]:
from tqdm import tqdm
## apply for the entire sentences
X = []
for i in tqdm(range(len(words))):
    
    X.append(avg_word2vec(words[i]))

100%|██████████| 5572/5572 [00:00<00:00, 9665.39it/s]

In [23]:
X

[array([-0.10057526,  0.2775405 ,  0.06252719,  0.08215357,  0.05107997,
        -0.39616627,  0.155614  ,  0.56439847, -0.16765067, -0.11926943,
        -0.17662396, -0.4244738 , -0.01474523,  0.11962643,  0.08617495,
        -0.15655114,  0.12365969, -0.32265133, -0.03311326, -0.45951524,
         0.22531904,  0.13898385,  0.15934655, -0.18209338, -0.09784514,
         0.05237969, -0.30952677, -0.15073597, -0.08587303,  0.04599514,
         0.34436306,  0.01352993,  0.12365502, -0.15337741, -0.14898884,
         0.3053576 ,  0.02711904, -0.24122334, -0.13057001, -0.38219866,
         0.00685379, -0.23220716, -0.07142131,  0.05633751,  0.19315107,
        -0.09968449, -0.2959516 , -0.0799095 ,  0.03714686,  0.14548835,
         0.12776002, -0.1428762 ,  0.01605835, -0.02888819, -0.14262727,
         0.07266473,  0.18993013,  0.02267069, -0.2625124 ,  0.20179856,
         0.01538041, -0.03169113,  0.030975  , -0.02337662, -0.2733267 ,
         0.22462477,  0.07628363,  0.16027561, -0.39304432,  0.37519863,
        -0.18555447,  0.13370392,  0.26074332,  0.01266597,  0.28412393,
         0.02534036, -0.01546905, -0.02714864, -0.1582942 ,  0.07337514,
        -0.11028673,  0.04772115, -0.3166239 ,  0.3241227 ,  0.04544712,
         0.07645997,  0.15220405,  0.29915756,  0.33717892, -0.06088398,
         0.3940813 ,  0.17692553,  0.02741381, -0.04438627,  0.34538585,
         0.3202906 ,  0.19892068, -0.22029328,  0.09675481, -0.05389398],
       dtype=float32),
 array([-0.07635202,  0.19685234,  0.04626738,  0.05662122,  0.03829655,
        -0.27300373,  0.09865355,  0.3917872 , -0.12176949, -0.07826496,
        -0.12521431, -0.29864392, -0.01294349,  0.08579445,  0.05413709,
        -0.1132606 ,  0.08687562, -0.22648855, -0.02430405, -0.32551348,
         0.15473278,  0.09972597,  0.10486809, -0.1338902 , -0.06479916,
         0.03724248, -0.2234933 , -0.10941643, -0.05571939,  0.03351398,
         0.2415377 ,  0.0134931 ,  0.08839891, -0.10861544, -0.11035717,
         0.21688795,  0.01072123, -0.17052047, -0.08899728, -0.27440017,
         0.00633254, -0.16944206, -0.05455967,  0.0399748 ,  0.13153298,
        -0.07814263, -0.20379572, -0.05353901,  0.02546   ,  0.10373441,
         0.09677613, -0.10572729,  0.01261059, -0.02383491, -0.10747638,
         0.05274835,  0.13412033,  0.01313945, -0.18456389,  0.14437641,
         0.00973126, -0.02394632,  0.01631012, -0.01424904, -0.19581203,
         0.14994824,  0.05207188,  0.11308549, -0.26921698,  0.26880565,
        -0.13042085,  0.10017303,  0.18566479,  0.01002175,  0.20331836,
         0.01269031, -0.00280394, -0.02639212, -0.10784332,  0.04598746,
        -0.07514229,  0.03415644, -0.2315519 ,  0.22882582,  0.03656523,
         0.05845386,  0.11172556,  0.2102805 ,  0.24087262, -0.04953279,
         0.2728196 ,  0.12213749,  0.02113464, -0.02972426,  0.24149455,
         0.22735019,  0.14066835, -0.15941812,  0.07546699, -0.04395227],
       dtype=float32),
 array([-0.10380299,  0.31977853,  0.05193629,  0.06917688,  0.06279267,
        -0.4148279 ,  0.14666058,  0.62456834, -0.17936295, -0.14323963,
        -0.19384222, -0.46575573, -0.02562253,  0.11969342,  0.0858933 ,
        -0.17165764,  0.1501533 , -0.36248222, -0.00864295, -0.50362265,
         0.23082112,  0.15689744,  0.16732669, -0.20629421, -0.09770124,
         0.06304746, -0.3515755 , -0.15267862, -0.10040642,  0.03886969,
         0.37834996,  0.02757133,  0.1417937 , -0.153429  , -0.18470307,
         0.33623192,  0.02903378, -0.27054107, -0.12530996, -0.41164306,
         0.0100131 , -0.2477429 , -0.08185003,  0.05157917,  0.20614289,
        -0.12936379, -0.3193061 , -0.08103785,  0.03911905,  0.15612556,
         0.13457419, -0.14500612,  0.0348332 , -0.02634889, -0.1691007 ,
         0.07331217,  0.21411328,  0.01792919, -0.29330307,  0.23526755,
         0.02282822, -0.0273484 ,  0.04621504, -0.01543911, -0.29127553,
         0.24951099,  0.08157805,  0.18845387, -0.42414185,  0.41479734,
        -0.19249927,  0.16452718,  0.26240924,  0.00145962,  0.31777394,
         0.0130452 , -0.02230706, -0.03758185, -0.14798631,  0.05291654,
        -0.10994402,  0.04824343, -0.3427708 ,  0.37965402,  0.06433757,
         0.09269931,  0.16378148,  0.33659753,  0.36263707, -0.06929304,
         0.43572503,  0.19121079,  0.00489283, -0.03718208,  0.3654002 ,
         0.3640744 ,  0.22709808, -0.24803215,  0.11271519, -0.05420983],
       dtype=float32),
 array([-0.14908557,  0.40421134,  0.10696646,  0.13405225,  0.07330036,
        -0.5751376 ,  0.23404217,  0.8087846 , -0.25326583, -0.17864323,
        -0.25615543, -0.6141526 , -0.01506061,  0.17407611,  0.12609683,
        -0.22401975,  0.183852  , -0.47605282, -0.05012357, -0.6806058 ,
         0.31872663,  0.20788582,  0.22755544, -0.26456276, -0.13793324,
         0.08980866, -0.4471303 , -0.21199474, -0.12056721,  0.06654002,
         0.49072403,  0.01001017,  0.16752999, -0.22209573, -0.21772613,
         0.43577433,  0.04876474, -0.34955135, -0.1910322 , -0.5622998 ,
         0.01063739, -0.34567118, -0.10501773,  0.09029161,  0.27701107,
        -0.15617216, -0.41928563, -0.11542593,  0.04678724,  0.21553676,
         0.19173266, -0.21107323,  0.01844385, -0.03051057, -0.2235854 ,
         0.12070598,  0.26947182,  0.03183506, -0.3758562 ,  0.29664364,
         0.02699538, -0.04898771,  0.03789177, -0.03111887, -0.3870719 ,
         0.31505194,  0.1129624 ,  0.22341193, -0.5625958 ,  0.544576  ,
        -0.27089104,  0.20242877,  0.38247135,  0.0157475 ,  0.41278696,
         0.03389331, -0.02779743, -0.02635864, -0.22824693,  0.10461418,
        -0.15234844,  0.06686022, -0.46644044,  0.45046237,  0.06993804,
         0.11147774,  0.22524776,  0.43491668,  0.47727197, -0.09184555,
         0.5615947 ,  0.26089427,  0.03824924, -0.05752211,  0.51248413,
         0.45898014,  0.30061108, -0.32694748,  0.14907515, -0.08175428],
       dtype=float32),
 array([-0.13620584,  0.3626493 ,  0.08789328,  0.11590553,  0.06844541,
        -0.5084016 ,  0.21231753,  0.7135412 , -0.22558291, -0.1542208 ,
        -0.22948682, -0.5361709 , -0.00920773,  0.15055072,  0.11877403,
        -0.19659175,  0.16228981, -0.41991556, -0.04808908, -0.60711575,
         0.27204037,  0.17828469,  0.20172565, -0.23647068, -0.12559213,
         0.08134035, -0.39784527, -0.1991006 , -0.11469201,  0.05839434,
         0.4315376 ,  0.01236292,  0.1467598 , -0.19069278, -0.18631016,
         0.39198303,  0.04467568, -0.2970445 , -0.16533647, -0.48844194,
         0.00916212, -0.30203214, -0.09648865,  0.07998133,  0.23468786,
        -0.12288431, -0.36819616, -0.09885529,  0.04362449,  0.19516969,
         0.15924436, -0.18441664,  0.01790001, -0.02516762, -0.19852227,
         0.10574823,  0.23752904,  0.027621  , -0.33486032,  0.2752228 ,
         0.02848051, -0.0416363 ,  0.03340841, -0.02718179, -0.33469963,
         0.2741455 ,  0.09497321,  0.2029603 , -0.49306965,  0.47736296,
        -0.23721342,  0.17454357,  0.33634984,  0.02073178,  0.36300722,
         0.02557648, -0.0306698 , -0.02288352, -0.19347577,  0.08945056,
        -0.1341045 ,  0.0647309 , -0.40443063,  0.38434234,  0.05739566,
         0.09949365,  0.20152785,  0.37654456,  0.41911206, -0.09225974,
         0.49928746,  0.23081751,  0.03302341, -0.0512798 ,  0.4512783 ,
         0.4023337 ,  0.25499037, -0.2934129 ,  0.12276906, -0.07314978],
       dtype=float32),
 array([-0.13287775,  0.38388443,  0.08635147,  0.10577822,  0.07094925,
        -0.53087246,  0.20907328,  0.75777984, -0.23136084, -0.17154089,
        -0.23896296, -0.5720186 , -0.02169688,  0.1565107 ,  0.11887972,
        -0.20824449,  0.17378356, -0.4409234 , -0.03851686, -0.6330956 ,
         0.2866321 ,  0.19030754,  0.2109581 , -0.25248885, -0.12583044,
         0.08225963, -0.41995436, -0.19982767, -0.1194303 ,  0.05792487,
         0.4602162 ,  0.01802901,  0.16533892, -0.1972693 , -0.20497225,
         0.4152878 ,  0.04350295, -0.31692225, -0.1663503 , -0.5096204 ,
         0.01543997, -0.31564188, -0.10317099,  0.07474168,  0.2522422 ,
        -0.13828887, -0.38889363, -0.10518315,  0.04908556,  0.20263027,
         0.16858731, -0.19100925,  0.02534636, -0.03348878, -0.20569985,
         0.10423172,  0.25704515,  0.02703591, -0.3533692 ,  0.29033542,
         0.02770555, -0.03850128,  0.04612743, -0.0256005 , -0.3537396 ,
         0.3012639 ,  0.10295184,  0.22152402, -0.5215129 ,  0.50527346,
        -0.24276389,  0.18503836,  0.34246957,  0.01940597,  0.38564527,
         0.02496533, -0.02890109, -0.03375254, -0.19626474,  0.08685751,
        -0.13921782,  0.06468867, -0.4231761 ,  0.42740843,  0.06677448,
         0.1033229 ,  0.21137916,  0.3986058 ,  0.44636312, -0.09121777,
         0.5308066 ,  0.24100143,  0.02531212, -0.05465763,  0.4656905 ,
         0.4308768 ,  0.27088425, -0.30562246,  0.12897629, -0.07336554],
       dtype=float32),
 array([-0.14059532,  0.39930502,  0.10089675,  0.12955579,  0.07167056,
        -0.562128  ,  0.23723906,  0.7892774 , -0.25079957, -0.17569838,
        -0.24788474, -0.5978006 , -0.01088296,  0.16886528,  0.13079986,
        -0.21820824,  0.17830087, -0.46214145, -0.05561517, -0.66419494,
         0.30706745,  0.20278397,  0.22644623, -0.26674527, -0.13993171,
         0.0871517 , -0.44013214, -0.21831468, -0.12570126,  0.05897199,
         0.47816068,  0.01758482,  0.16597041, -0.21338902, -0.20774303,
         0.4315615 ,  0.04386972, -0.32735837, -0.18681408, -0.53945047,
         0.01617118, -0.33352798, -0.10477404,  0.08234832,  0.26594976,
        -0.13303095, -0.4111175 , -0.11441445,  0.04578942,  0.21484813,
         0.1784263 , -0.20413235,  0.01709817, -0.03737184, -0.21770786,
         0.11502432,  0.26589537,  0.02899126, -0.36592022,  0.30369893,
         0.02623601, -0.04818111,  0.0466592 , -0.03378888, -0.3719578 ,
         0.3152014 ,  0.1017487 ,  0.22868004, -0.54912615,  0.526222  ,
        -0.2575236 ,  0.19320272,  0.3731794 ,  0.02401837,  0.40025106,
         0.03076179, -0.03059151, -0.0326908 , -0.21478906,  0.09577835,
        -0.15062651,  0.07218261, -0.44712374,  0.431817  ,  0.07047853,
         0.10504865,  0.22858113,  0.41841638,  0.4712475 , -0.09552122,
         0.5519403 ,  0.2512508 ,  0.03412534, -0.05930125,  0.4972502 ,
         0.44725117,  0.27999976, -0.32196343,  0.13554443, -0.08128851],
       dtype=float32),
 array([-0.09116444,  0.29142022,  0.06172837,  0.06750066,  0.05159578,
        -0.40075877,  0.14180039,  0.5879344 , -0.1761523 , -0.1305324 ,
        -0.18509705, -0.44573337, -0.01897083,  0.11929182,  0.08788846,
        -0.16088678,  0.13776188, -0.34087428, -0.01671572, -0.4765093 ,
         0.2226057 ,  0.14377895,  0.15864205, -0.1972199 , -0.09401552,
         0.05557945, -0.32895947, -0.14479776, -0.08672103,  0.03431608,
         0.35842633,  0.02515845,  0.13582644, -0.14182372, -0.1669705 ,
         0.3204337 ,  0.0354701 , -0.24845   , -0.12559672, -0.38949487,
         0.00886529, -0.23553525, -0.08028189,  0.05550157,  0.1877099 ,
        -0.10871974, -0.29981542, -0.0782051 ,  0.03480094,  0.15591013,
         0.12389039, -0.13857594,  0.02848587, -0.02941688, -0.14843515,
         0.0728813 ,  0.20313188,  0.01724162, -0.26996017,  0.21915223,
         0.00809911, -0.02487174,  0.03985605, -0.0173678 , -0.2839145 ,
         0.24354315,  0.07059546,  0.16762176, -0.4042227 ,  0.3857715 ,
        -0.1796588 ,  0.15273002,  0.2608822 ,  0.02055801,  0.29970303,
         0.02064841, -0.01921705, -0.03657081, -0.14783569,  0.07021404,
        -0.10376912,  0.05287089, -0.3181742 ,  0.35530114,  0.05799576,
         0.08164495,  0.15435779,  0.3123128 ,  0.35138693, -0.06627167,
         0.4128208 ,  0.1873715 ,  0.01349521, -0.042211  ,  0.34590754,
         0.33929706,  0.20892136, -0.23151624,  0.10200765, -0.05509749],
       dtype=float32),
 array([-0.11783928,  0.36649916,  0.06325439,  0.07661852,  0.07846767,
        -0.4672541 ,  0.16525131,  0.7232407 , -0.2058678 , -0.16413005,
        -0.24093454, -0.54438376, -0.04090752,  0.12712802,  0.09706414,
        -0.20563091,  0.18025662, -0.39980847, -0.00354386, -0.5705155 ,
         0.26341808,  0.17430335,  0.19165947, -0.24399465, -0.10310284,
         0.07827156, -0.42278466, -0.16842169, -0.10430279,  0.04782265,
         0.44618797,  0.03569466,  0.17121284, -0.17943694, -0.22417797,
         0.38405225,  0.03727371, -0.30867958, -0.12809576, -0.46285343,
         0.00686186, -0.28301278, -0.09952302,  0.05967519,  0.23106702,
        -0.16346318, -0.36139044, -0.08987071,  0.04011451,  0.1816666 ,
         0.15487912, -0.181221  ,  0.05105707, -0.03873443, -0.20013246,
         0.08980752,  0.25278994,  0.02918228, -0.32722747,  0.28303158,
         0.02660626, -0.03124104,  0.06253093, -0.00584383, -0.3311161 ,
         0.2897737 ,  0.08825186,  0.2224118 , -0.48601192,  0.48183823,
        -0.22516173,  0.19077381,  0.30261692,  0.00141665,  0.37563097,
         0.00529492, -0.01649944, -0.05103738, -0.15551251,  0.06252637,
        -0.11759777,  0.0636963 , -0.38326317,  0.45554453,  0.07910178,
         0.10616648,  0.19595847,  0.38821083,  0.4058282 , -0.10111309,
         0.5224746 ,  0.22914577,  0.00531433, -0.05123819,  0.42344528,
         0.4239244 ,  0.26795965, -0.28250542,  0.12520313, -0.0613041 ],
       dtype=float32),
 array([-1.10533021e-01,  4.03804094e-01,  6.79261684e-02,  7.13175684e-02,
         8.81129280e-02, -5.15838802e-01,  1.70793012e-01,  7.95638800e-01,
        -2.24686101e-01, -1.79731920e-01, -2.53273517e-01, -6.04317188e-01,
        -4.02558744e-02,  1.48911625e-01,  1.03395253e-01, -2.18292430e-01,
         1.93764567e-01, -4.51026678e-01,  6.98606856e-03, -6.09744132e-01,
         2.86591619e-01,  1.96769640e-01,  2.10750520e-01, -2.62035102e-01,
        -1.13898128e-01,  7.46894851e-02, -4.42459017e-01, -1.83295861e-01,
        -1.27104864e-01,  4.42961119e-02,  4.86493796e-01,  4.23104092e-02,
         1.82280794e-01, -1.80794924e-01, -2.48870805e-01,  4.24442112e-01,
         3.80746610e-02, -3.41526061e-01, -1.50729820e-01, -5.13381064e-01,
         1.25836302e-02, -3.07375401e-01, -1.03788145e-01,  5.98003007e-02,
         2.51053780e-01, -1.61331803e-01, -4.01765227e-01, -1.03446849e-01,
         4.81630862e-02,  1.93078175e-01,  1.74986824e-01, -1.91067278e-01,
         5.60762063e-02, -4.52201143e-02, -2.03571409e-01,  8.39064568e-02,
         2.80407995e-01,  2.99435332e-02, -3.63053501e-01,  2.88585067e-01,
         1.71917193e-02, -2.81434655e-02,  6.84127286e-02, -7.89779145e-03,
        -3.73440593e-01,  3.26802939e-01,  9.77428928e-02,  2.36320764e-01,
        -5.39917946e-01,  5.23231804e-01, -2.30219662e-01,  2.12106302e-01,
         3.30809027e-01,  7.27674516e-04,  4.09396142e-01,  1.41669204e-02,
        -2.64908411e-02, -6.11995272e-02, -1.86432853e-01,  7.54132569e-02,
        -1.33387819e-01,  5.57826944e-02, -4.33954686e-01,  4.97361898e-01,
         8.57970789e-02,  1.09899953e-01,  2.03904822e-01,  4.31939214e-01,
         4.61180270e-01, -8.71795341e-02,  5.59305131e-01,  2.47136116e-01,
         1.80370873e-03, -4.49298248e-02,  4.52369690e-01,  4.67010617e-01,
         2.85274565e-01, -3.08365911e-01,  1.49740279e-01, -6.65888488e-02],
       dtype=float32),
 array([-0.13537651,  0.36972532,  0.08679789,  0.11142308,  0.06905692,
        -0.5119172 ,  0.21544468,  0.72348   , -0.22656003, -0.15892996,
        -0.23202232, -0.5433591 , -0.0179232 ,  0.15220904,  0.11925693,
        -0.19823976,  0.16744685, -0.420079  , -0.0476493 , -0.61558086,
         0.27444243,  0.1831796 ,  0.20614412, -0.23986197, -0.12223517,
         0.08667821, -0.40531138, -0.19669977, -0.11350247,  0.06107537,
         0.43479368,  0.01536953,  0.15626793, -0.1905599 , -0.19015932,
         0.4009629 ,  0.04467445, -0.2974293 , -0.16486019, -0.49208674,
         0.01012369, -0.30659732, -0.09364104,  0.07856832,  0.23871674,
        -0.13292965, -0.37057656, -0.10272979,  0.04279809,  0.195997  ,
         0.16260234, -0.18204182,  0.01932891, -0.03287889, -0.2036613 ,
         0.10248306,  0.24183576,  0.03125041, -0.33634257,  0.28354964,
         0.02923913, -0.04105235,  0.0403712 , -0.02814276, -0.33660161,
         0.28371975,  0.1000636 ,  0.21406615, -0.50122434,  0.4843741 ,
        -0.2348111 ,  0.17381322,  0.33563423,  0.0250495 ,  0.37081614,
         0.0239289 , -0.03003705, -0.02454877, -0.19386862,  0.08864081,
        -0.13383782,  0.06713647, -0.40425172,  0.3954738 ,  0.06047487,
         0.09755406,  0.20686813,  0.38211054,  0.42577755, -0.09235866,
         0.509051  ,  0.23286764,  0.03413788, -0.05488155,  0.45400617,
         0.40644526,  0.26347104, -0.2948165 ,  0.12212311, -0.07213656],
       dtype=float32),
 array([-0.12652393,  0.38939893,  0.05952282,  0.08219594,  0.08126619,
        -0.49797043,  0.17885368,  0.75721496, -0.21818566, -0.180411  ,
        -0.23440844, -0.5661602 , -0.03429103,  0.13846597,  0.10132609,
        -0.2112217 ,  0.18788819, -0.4409366 , -0.0064906 , -0.6067776 ,
         0.2762549 ,  0.18853968,  0.20200686, -0.25526053, -0.11577353,
         0.07394507, -0.43045628, -0.1845983 , -0.12156734,  0.04629917,
         0.4604958 ,  0.03289388,  0.17189534, -0.18491572, -0.22660974,
         0.40383628,  0.03740446, -0.32605973, -0.14552258, -0.4951638 ,
         0.01719746, -0.2983327 , -0.09905538,  0.06217955,  0.24525891,
        -0.15945072, -0.3848426 , -0.09790725,  0.04738458,  0.19030403,
         0.1591056 , -0.17696697,  0.04082804, -0.03028578, -0.20483522,
         0.08756687,  0.26295808,  0.02291617, -0.35155666,  0.28828287,
         0.02586365, -0.0291345 ,  0.05959474, -0.01455639, -0.34945118,
         0.30392715,  0.08999269,  0.2344153 , -0.51008797,  0.50065076,
        -0.22935677,  0.20034426,  0.3156972 ,  0.00153781,  0.38597533,
         0.01136993, -0.02658449, -0.04742351, -0.17862219,  0.0613503 ,
        -0.12769543,  0.05767727, -0.40847802,  0.46618706,  0.08193799,
         0.11212982,  0.20009701,  0.4073046 ,  0.4373396 , -0.08591135,
         0.5301315 ,  0.23203754,  0.00246174, -0.0456139 ,  0.44004855,
         0.44280884,  0.2780405 , -0.30320504,  0.13445912, -0.06647833],
       dtype=float32),
 array([-0.13090761,  0.41294158,  0.06561401,  0.08203039,  0.08715925,
        -0.53071165,  0.18836942,  0.80539536, -0.24016744, -0.18258642,
        -0.2618224 , -0.60955304, -0.03624277,  0.14440449,  0.10916425,
        -0.2245585 ,  0.19838494, -0.46245846, -0.00669006, -0.643228  ,
         0.28909907,  0.19807072,  0.2135841 , -0.26812577, -0.12278756,
         0.08462174, -0.46447396, -0.19273686, -0.12287945,  0.04799505,
         0.49781013,  0.04145946,  0.1840431 , -0.19128378, -0.24466495,
         0.43338704,  0.04046379, -0.34286356, -0.15512337, -0.5194376 ,
         0.01748491, -0.3206858 , -0.1092    ,  0.06872406,  0.26358274,
        -0.17325552, -0.4053851 , -0.10450988,  0.04614189,  0.19862378,
         0.17544366, -0.19701864,  0.05265518, -0.04072607, -0.2255143 ,
         0.09104872,  0.28174415,  0.02654272, -0.37681365,  0.31034008,
         0.02730687, -0.033424  ,  0.07157705, -0.01158893, -0.3732185 ,
         0.32815433,  0.10438436,  0.24563551, -0.5437086 ,  0.54023474,
        -0.244767  ,  0.20943153,  0.33480158,  0.0070348 ,  0.4173852 ,
         0.01532864, -0.02747609, -0.05333062, -0.18066554,  0.07009739,
        -0.13552955,  0.06467631, -0.4365356 ,  0.49397776,  0.08673828,
         0.11977197,  0.21447498,  0.43628824,  0.46105456, -0.10045967,
         0.5731982 ,  0.25206408,  0.00766794, -0.0566446 ,  0.4664113 ,
         0.46982354,  0.30064118, -0.31892213,  0.14560825, -0.06955495],
       dtype=float32),
 array([-0.13244767,  0.37270597,  0.08499476,  0.10557886,  0.07283385,
        -0.51618236,  0.20760895,  0.7316857 , -0.23249388, -0.162053  ,
        -0.2360966 , -0.5588796 , -0.01582595,  0.15551178,  0.12349365,

In [24]:
len(X)

5572

In [25]:
X_new = np.array(X)

In [26]:
X_new[0].shape

(100,)

In [30]:
## dependent feature 
## ouput feature
y = messages[list(map(lambda x:len(x)>0,corpus))]
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [31]:
y.shape

(5572,)

## part 2 of text Classification with word2vec and AvgWord2Vec

In [40]:
X[0].reshape(1,-1)

array([[-0.10057526,  0.2775405 ,  0.06252719,  0.08215357,  0.05107997,
        -0.39616627,  0.155614  ,  0.56439847, -0.16765067, -0.11926943,
        -0.17662396, -0.4244738 , -0.01474523,  0.11962643,  0.08617495,
        -0.15655114,  0.12365969, -0.32265133, -0.03311326, -0.45951524,
         0.22531904,  0.13898385,  0.15934655, -0.18209338, -0.09784514,
         0.05237969, -0.30952677, -0.15073597, -0.08587303,  0.04599514,
         0.34436306,  0.01352993,  0.12365502, -0.15337741, -0.14898884,
         0.3053576 ,  0.02711904, -0.24122334, -0.13057001, -0.38219866,
         0.00685379, -0.23220716, -0.07142131,  0.05633751,  0.19315107,
        -0.09968449, -0.2959516 , -0.0799095 ,  0.03714686,  0.14548835,
         0.12776002, -0.1428762 ,  0.01605835, -0.02888819, -0.14262727,
         0.07266473,  0.18993013,  0.02267069, -0.2625124 ,  0.20179856,
         0.01538041, -0.03169113,  0.030975  , -0.02337662, -0.2733267 ,
         0.22462477,  0.07628363,  0.16027561, -0.39304432,  0.37519863,
        -0.18555447,  0.13370392,  0.26074332,  0.01266597,  0.28412393,
         0.02534036, -0.01546905, -0.02714864, -0.1582942 ,  0.07337514,
        -0.11028673,  0.04772115, -0.3166239 ,  0.3241227 ,  0.04544712,
         0.07645997,  0.15220405,  0.29915756,  0.33717892, -0.06088398,
         0.3940813 ,  0.17692553,  0.02741381, -0.04438627,  0.34538585,
         0.3202906 ,  0.19892068, -0.22029328,  0.09675481, -0.05389398]],
      dtype=float32)

In [43]:
## this is the final independent features

df = pd.DataFrame()

for i in range(0, len(X)):
    df = pd.concat(
        [df, pd.DataFrame(X[i].reshape(1, -1))],
        ignore_index=True
    )

In [44]:
df.shape

(5572, 100)

In [45]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.100575,0.277541,0.062527,0.082154,0.051080,-0.396166,0.155614,0.564398,-0.167651,-0.119269,...,0.394081,0.176926,0.027414,-0.044386,0.345386,0.320291,0.198921,-0.220293,0.096755,-0.053894
1,-0.076352,0.196852,0.046267,0.056621,0.038297,-0.273004,0.098654,0.391787,-0.121769,-0.078265,...,0.272820,0.122137,0.021135,-0.029724,0.241495,0.227350,0.140668,-0.159418,0.075467,-0.043952
2,-0.103803,0.319779,0.051936,0.069177,0.062793,-0.414828,0.146661,0.624568,-0.179363,-0.143240,...,0.435725,0.191211,0.004893,-0.037182,0.365400,0.364074,0.227098,-0.248032,0.112715,-0.054210
3,-0.149086,0.404211,0.106966,0.134052,0.073300,-0.575138,0.234042,0.808785,-0.253266,-0.178643,...,0.561595,0.260894,0.038249,-0.057522,0.512484,0.458980,0.300611,-0.326947,0.149075,-0.081754
4,-0.136206,0.362649,0.087893,0.115906,0.068445,-0.508402,0.212318,0.713541,-0.225583,-0.154221,...,0.499287,0.230818,0.033023,-0.051280,0.451278,0.402334,0.254990,-0.293413,0.122769,-0.073150

In [46]:
## independent Feature
X =df

In [52]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [47]:
## tss 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [50]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [51]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [53]:
y_pred = classifier.predict(X_test)

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[128  21]
 [ 12 954]]
0.9704035874439462
              precision    recall  f1-score   support

       False       0.91      0.86      0.89       149
        True       0.98      0.99      0.98       966

    accuracy                           0.97      1115
   macro avg       0.95      0.92      0.93      1115
weighted avg       0.97      0.97      0.97      1115